In [1]:
import numpy as np

In [2]:
# create a 1d array
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(5,)


In [7]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  # 1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [9]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr2.shape

(2, 5)

In [10]:
print(arr2)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [11]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
new_arr=np.array([[1,2,3],[4,5,6]])

print("Arrya:\n",new_arr)
print("Shape:\n",new_arr.shape)
print("No of dimensions:\n",new_arr.ndim)
print("Size (number of elements)",new_arr.size)
print("Data type",new_arr.dtype)
print("Item size (in bytes)",new_arr.itemsize)

Arrya:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
No of dimensions:
 2
Size (number of elements) 6
Data type int64
Item size (in bytes) 8


In [16]:
# Numpy vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
# Element Wise addition
print(arr1+arr2)
# Element Wise Substraction
print(arr1-arr2)
# Element Wise Multiplication
print(arr1*arr2)
# Element Wise Division
print(arr1/arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [17]:
#Universal Function
arr=np.array([2,3,4,5,6])
##Square root
print(np.sqrt(arr))
##Exponential
print(np.exp(arr))
##Logarithmic
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [20]:
#Array Slicing and Indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [25]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
arr[0][0]

np.int64(1)

In [27]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [28]:
arr[0,0]=100

In [29]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [30]:
##Statistical concept--Normalization
#to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

#Calculate the mean and standard deviation
mean=np.mean(data)
std=np.std(data)

#Normalize the data
normalized_data=(data-mean)/std

print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [32]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean=np.mean(data)
print(mean)

# Median
median=np.median(data)
print(median)

# Standard deviation
std_dev=np.std(data)
print(std_dev)

#Variance
Variance=np.var(data)
print(Variance)

5.5
5.5
2.8722813232690143
8.25


In [33]:
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
data[data>5]

array([ 6,  7,  8,  9, 10])